global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "stabuse_service"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/metrics"

  - job_name: "postgres_metrics"
    static_configs:
      - targets: ["postgres:9187"]
